import mongoose from "mongoose";
import Furniture from "./models/furniture.js";
import Fabric from "./models/fabric.js";
import FabricFurn from "./models/fabricFurn.js";
import FabricColor from "./models/fabricColor.js";

const MONGO_URI =
  "mongodb+srv://craft14716:Ul9fxfBZ99WkOyuF@cluster0.yekbwzy.mongodb.net/furniture?retryWrites=true&w=majority&appName=Cluster0";

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("DB Connected");

    await Furniture.deleteMany();
    await Fabric.deleteMany();
    await FabricFurn.deleteMany();
    await FabricColor.deleteMany();

    const furnitures = await Furniture.insertMany([
      {
        name: "كنبة عصرية",
        description: "كنبة عصرية مريحة بتصميم أنيق",
        category: "sofa",
        thumbnail: "/img-1.webp",
      },
      {
        name: "كنبة كلاسيكية",
        description: "كنبة كلاسيكية فاخرة بأناقة تقليدية",
        category: "sofa",
        thumbnail: "/img-2.webp",
      },
      {
        name: "كنبة على شكل L معاصرة",
        description: "كنبة واسعة على شكل L مثالية لغرف المعيشة الحديثة",
        category: "sofa",
        thumbnail: "/img-3.webp",
      },
      {
        name: "كنبة بسيطة متعددة الأقسام",
        description: "كنبة بخطوط نظيفة وراحة قصوى",
        category: "sofa",
        thumbnail: "/img-4.webp",
      },
      {
        name: "كنبة فاخرة قابلة للإستلقاء",
        description: "كنبة قابلة للإستلقاء متميزة بآليات متطورة",
        category: "sofa",
        thumbnail: "/img-5.webp",
      },
      {
        name: "كنبة اسكندنافية",
        description: "كنبة مستوحاة من الطراز الشمالي بمواد طبيعية",
        category: "sofa",
        thumbnail: "/img-6.webp",
      },
      {
        name: "كنبة تشيسترفيلد فيكتورية",
        description: "كنبة تشيسترفيلد مزخرفة بتفاصيل منجدة",
        category: "sofa",
        thumbnail: "/img-7.webp",
      },
      {
        name: "كنبة معاصرة",
        description: "كنبة صغيرة مثالية للمساحات الضيقة",
        category: "sofa",
        thumbnail: "/img-8.webp",
      },
      {
        name: "نظام كنبة معياري",
        description: "كنبة معيارية مرنة تتكيف مع أي مساحة",
        category: "sofa",
        thumbnail: "/img-9.webp",
      },
      {
        name: "ستائر أنيقة - كتان",
        description: "ستائر كتان فاخرة بطيات ناعمة",
        category: "curtain",
        thumbnail: "/img-10.webp",
      },
      {
        name: "ستائر مخملية فاخرة",
        description: "ستائر مخملية غنية بملمس رائع",
        category: "curtain",
        thumbnail: "/img-11.webp",
      },
      {
        name: "ستائر شفافة من الفوال",
        description: "ستائر شفافة خفيفة للتصفية الناعمة للضوء",
        category: "curtain",
        thumbnail: "/img-1.webp",
      },
      {
        name: "ستائر حرارية معتمة",
        description: "ستائر معتمة فائقة التحمل للخصوصية والعزل",
        category: "curtain",
        thumbnail: "/img-2.webp",
      },
      {
        name: "ستائر بنقشة جاكار",
        description: "ستائر بنقشة جاكار أنيقة",
        category: "curtain",
        thumbnail: "/img-3.webp",
      },
      {
        name: "ستائر حديثة بسيطة",
        description: "تصميم نظيف وبسيط للمساحات المعاصرة",
        category: "curtain",
        thumbnail: "/img-4.webp",
      },
      {
        name: "ستائر بنقشة دمشقية",
        description: "نقشة دمشقية كلاسيكية بجاذبية خالدة",
        category: "curtain",
        thumbnail: "/img-5.webp",
      },
      {
        name: "ستائر حرير مجعد",
        description: "حرير مجعد فاخر بطيات أنيقة",
        category: "curtain",
        thumbnail: "/img-6.webp",
      },
      {
        name: "ستائر بنقشة هندسية",
        description: "تصاميم هندسية معاصرة للديكورات الحديثة",
        category: "curtain",
        thumbnail: "/img-7.webp",
      },
      {
        name: "ستائر بطبعة زهور",
        description: "طبعات زهور جميلة لغرف مبهجة",
        category: "curtain",
        thumbnail: "/img-8.webp",
      },
    ]);

    const fabrics = await Fabric.insertMany([
      { name: "قماش قطني", description: "قماش قطني ناعم" },
      { name: "قماش كتاني", description: "قماش كتاني طبيعي" },
      { name: "مايكروفايبر فاخر", description: "خليط مايكروفايبر متميز" },
      { name: "قماش مخمل", description: "قماش مخملي فاخر" },
      { name: "جلد منجد", description: "جلد منجد فاخر" },
      { name: "خليط حريري", description: "خليط حرير وقطن" },
      { name: "قماش مايكروفايبر", description: "قماش مايكروفايبر متين" },
      { name: "خليط بوليستر", description: "خليط بوليستر مريح" },
      { name: "قماش صوفي", description: "قماش صوفي فاخر" },
      { name: "ساتان قطني", description: "ساتان قطني فاخر" },
      { name: "قماش سويدي", description: "قماش سويدي ناعم" },
      { name: "جلد فاخر", description: "جلد منجد متميز" },
      { name: "جلد نوبوك", description: "جلد نوبوك فاخر" },
      { name: "كتان طبيعي", description: "كتان طبيعي منجد" },
      { name: "خليط صوفي", description: "خليط صوفي منجد" },
      { name: "قماش جاكار", description: "قماش جاكار منقوش" },
      { name: "مخمل تقليدي", description: "مخمل تقليدي منجد" },
      { name: "قماش كانفاس", description: "قماش كانفاس متين" },
      { name: "كتان فاخر", description: "قماش كتاني فاخر" },
      { name: "خليط نايلون", description: "خليط نايلون متين" },
      { name: "بوليستر فاخر", description: "بوليستر فاخر منجد" },
      { name: "مايكروسويد", description: "مايكروسويد ناعم منجد" },
      { name: "كتان طبيعي", description: "كتان طبيعي نقي" },
      { name: "خليط كتاني", description: "خليط كتان وقطن" },
      { name: "مخمل فاخر", description: "مخمل فاخر للستائر" },
      { name: "خليط مخملي", description: "خليط مخمل وحرير" },
      { name: "فوال شفاف", description: "قماش فوال شفاف خفيف" },
      { name: "أورجانزا شفافة", description: "أورجانزا شفافة رقيقة" },
      { name: "بوليستر معتم", description: "بوليستر معتم ثقيل" },
      { name: "قماش حراري مبطن", description: "قماش حراري معتم مبطن" },
      { name: "نسيج جاكار", description: "نسيج جاكار منقوش" },
      { name: "خليط جاكار", description: "خليط جاكار قطني" },
      { name: "قطن بسيط", description: "خليط قطني بسيط" },
      { name: "كتان نقي", description: "قماش كتاني نقي" },
      { name: "خليط دمشقي", description: "خليط بنقشة دمشقية" },
      { name: "جاكار دمشقي", description: "نسيج جاكار دمشقي" },
      { name: "حرير مجعد", description: "حرير مجعد فاخر" },
      { name: "حرير خام", description: "قماش حرير خام" },
      { name: "قطن هندسي", description: "قطن بنقشات هندسية" },
      { name: "بوليستر هندسي", description: "خليط بوليستر هندسي" },
      { name: "خليط زهور", description: "خليط بنقشة زهور" },
      { name: "كتان زهور", description: "كتان بطبعة زهور" },
    ]);

    await FabricFurn.insertMany([
      { fabricId: fabrics[0]._id, furnId: furnitures[0]._id },
      { fabricId: fabrics[1]._id, furnId: furnitures[0]._id },
      { fabricId: fabrics[2]._id, furnId: furnitures[0]._id },
      { fabricId: fabrics[3]._id, furnId: furnitures[1]._id },
      { fabricId: fabrics[4]._id, furnId: furnitures[1]._id },
      { fabricId: fabrics[5]._id, furnId: furnitures[1]._id },
      { fabricId: fabrics[6]._id, furnId: furnitures[2]._id },
      { fabricId: fabrics[7]._id, furnId: furnitures[2]._id },
      { fabricId: fabrics[8]._id, furnId: furnitures[3]._id },
      { fabricId: fabrics[9]._id, furnId: furnitures[3]._id },
      { fabricId: fabrics[10]._id, furnId: furnitures[4]._id },
      { fabricId: fabrics[11]._id, furnId: furnitures[4]._id },
      { fabricId: fabrics[12]._id, furnId: furnitures[4]._id },
      { fabricId: fabrics[13]._id, furnId: furnitures[5]._id },
      { fabricId: fabrics[14]._id, furnId: furnitures[5]._id },
      { fabricId: fabrics[15]._id, furnId: furnitures[6]._id },
      { fabricId: fabrics[16]._id, furnId: furnitures[6]._id },
      { fabricId: fabrics[17]._id, furnId: furnitures[7]._id },
      { fabricId: fabrics[18]._id, furnId: furnitures[7]._id },
      { fabricId: fabrics[19]._id, furnId: furnitures[8]._id },
      { fabricId: fabrics[20]._id, furnId: furnitures[8]._id },
      { fabricId: fabrics[21]._id, furnId: furnitures[8]._id },
      { fabricId: fabrics[22]._id, furnId: furnitures[9]._id },
      { fabricId: fabrics[23]._id, furnId: furnitures[9]._id },
      { fabricId: fabrics[24]._id, furnId: furnitures[10]._id },
      { fabricId: fabrics[25]._id, furnId: furnitures[10]._id },
      { fabricId: fabrics[26]._id, furnId: furnitures[11]._id },
      { fabricId: fabrics[27]._id, furnId: furnitures[11]._id },
      { fabricId: fabrics[28]._id, furnId: furnitures[12]._id },
      { fabricId: fabrics[29]._id, furnId: furnitures[12]._id },
      { fabricId: fabrics[30]._id, furnId: furnitures[13]._id },
      { fabricId: fabrics[31]._id, furnId: furnitures[13]._id },
      { fabricId: fabrics[32]._id, furnId: furnitures[14]._id },
      { fabricId: fabrics[33]._id, furnId: furnitures[14]._id },
      { fabricId: fabrics[34]._id, furnId: furnitures[15]._id },
      { fabricId: fabrics[35]._id, furnId: furnitures[15]._id },
      { fabricId: fabrics[36]._id, furnId: furnitures[16]._id },
      { fabricId: fabrics[37]._id, furnId: furnitures[16]._id },
      { fabricId: fabrics[38]._id, furnId: furnitures[17]._id },
      { fabricId: fabrics[39]._id, furnId: furnitures[17]._id },
      { fabricId: fabrics[40]._id, furnId: furnitures[18]._id },
      { fabricId: fabrics[41]._id, furnId: furnitures[18]._id },
    ]);

    await FabricColor.insertMany([
      {
        fabricId: fabrics[0]._id,
        furnId: furnitures[0]._id,
        name: "بيج",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[0]._id,
        furnId: furnitures[0]._id,
        name: "رمادي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[0]._id,
        furnId: furnitures[0]._id,
        name: "كريمي",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[0]._id,
        furnId: furnitures[0]._id,
        name: "أزرق فاتح",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[1]._id,
        furnId: furnitures[0]._id,
        name: "أبيض",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[1]._id,
        furnId: furnitures[0]._id,
        name: "طبيعي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[1]._id,
        furnId: furnitures[0]._id,
        name: "قمحي",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[2]._id,
        furnId: furnitures[0]._id,
        name: "فحمي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[2]._id,
        furnId: furnitures[0]._id,
        name: "جرافيت",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[3]._id,
        furnId: furnitures[1]._id,
        name: "أزرق داكن",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[3]._id,
        furnId: furnitures[1]._id,
        name: "أخضر زمردي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[3]._id,
        furnId: furnitures[1]._id,
        name: "عنابي",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[3]._id,
        furnId: furnitures[1]._id,
        name: "بنفسجي ليلي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[4]._id,
        furnId: furnitures[1]._id,
        name: "أسود",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[4]._id,
        furnId: furnitures[1]._id,
        name: "كونياك",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[4]._id,
        furnId: furnitures[1]._id,
        name: "إسبريسو",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[5]._id,
        furnId: furnitures[1]._id,
        name: "شامبانيا",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[5]._id,
        furnId: furnitures[1]._id,
        name: "عاجي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[6]._id,
        furnId: furnitures[2]._id,
        name: "فحمي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[6]._id,
        furnId: furnitures[2]._id,
        name: "توب",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[6]._id,
        furnId: furnitures[2]._id,
        name: "أزرق إردوازي",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[7]._id,
        furnId: furnitures[2]._id,
        name: "كحلي",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[7]._id,
        furnId: furnitures[2]._id,
        name: "كاكي",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[7]._id,
        furnId: furnitures[2]._id,
        name: "ميرمية",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[8]._id,
        furnId: furnitures[3]._id,
        name: "جملي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[8]._id,
        furnId: furnitures[3]._id,
        name: "رمادي حجري",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[8]._id,
        furnId: furnitures[3]._id,
        name: "فحمي غامق",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[9]._id,
        furnId: furnitures[3]._id,
        name: "أبيض لؤلؤي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[9]._id,
        furnId: furnitures[3]._id,
        name: "رمادي ناعم",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[10]._id,
        furnId: furnitures[4]._id,
        name: "شوكولاتة",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[10]._id,
        furnId: furnitures[4]._id,
        name: "كراميل",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[10]._id,
        furnId: furnitures[4]._id,
        name: "موكا",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[11]._id,
        furnId: furnitures[4]._id,
        name: "أسود",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[11]._id,
        furnId: furnitures[4]._id,
        name: "بني داكن",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[12]._id,
        furnId: furnitures[4]._id,
        name: "تان",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[12]._id,
        furnId: furnitures[4]._id,
        name: "فحمي",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[13]._id,
        furnId: furnitures[5]._id,
        name: "كتان طبيعي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[13]._id,
        furnId: furnitures[5]._id,
        name: "أبيض مكسور",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[14]._id,
        furnId: furnitures[5]._id,
        name: "رمادي فاتح",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[14]._id,
        furnId: furnitures[5]._id,
        name: "شوفان",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[15]._id,
        furnId: furnitures[6]._id,
        name: "نبيذي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[15]._id,
        furnId: furnitures[6]._id,
        name: "نقشة ذهبية",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[16]._id,
        furnId: furnitures[6]._id,
        name: "أحمر داكن",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[16]._id,
        furnId: furnitures[6]._id,
        name: "أخضر غابات",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[17]._id,
        furnId: furnitures[7]._id,
        name: "شوفان",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[17]._id,
        furnId: furnitures[7]._id,
        name: "طبيعي",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[18]._id,
        furnId: furnitures[7]._id,
        name: "كريمي",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[18]._id,
        furnId: furnitures[7]._id,
        name: "توب",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[19]._id,
        furnId: furnitures[8]._id,
        name: "إردوازي",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[19]._id,
        furnId: furnitures[8]._id,
        name: "فحمي",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[20]._id,
        furnId: furnitures[8]._id,
        name: "أسود",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[20]._id,
        furnId: furnitures[8]._id,
        name: "رمادي",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[21]._id,
        furnId: furnitures[8]._id,
        name: "ضبابي",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[21]._id,
        furnId: furnitures[8]._id,
        name: "خشب طافي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[22]._id,
        furnId: furnitures[9]._id,
        name: "عاجي",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[22]._id,
        furnId: furnitures[9]._id,
        name: "رملي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[22]._id,
        furnId: furnitures[9]._id,
        name: "حجري",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[23]._id,
        furnId: furnitures[9]._id,
        name: "أخضر ميرمية",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[23]._id,
        furnId: furnitures[9]._id,
        name: "وردي ترابي",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[23]._id,
        furnId: furnitures[9]._id,
        name: "توب ناعم",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[24]._id,
        furnId: furnitures[10]._id,
        name: "أزرق ملكي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[24]._id,
        furnId: furnitures[10]._id,
        name: "برقوقي",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[24]._id,
        furnId: furnitures[10]._id,
        name: "فحمي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[25]._id,
        furnId: furnitures[10]._id,
        name: "زمردي",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[25]._id,
        furnId: furnitures[10]._id,
        name: "ياقوتي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[26]._id,
        furnId: furnitures[11]._id,
        name: "أبيض شفاف",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[26]._id,
        furnId: furnitures[11]._id,
        name: "أصفر باهت",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[26]._id,
        furnId: furnitures[11]._id,
        name: "كريمي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[27]._id,
        furnId: furnitures[11]._id,
        name: "أبيض كريستالي",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[27]._id,
        furnId: furnitures[11]._id,
        name: "لؤلؤي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[28]._id,
        furnId: furnitures[12]._id,
        name: "أسود غامق",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[28]._id,
        furnId: furnitures[12]._id,
        name: "رمادي داكن",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[28]._id,
        furnId: furnitures[12]._id,
        name: "كحلي",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[29]._id,
        furnId: furnitures[12]._id,
        name: "أسود مبطن",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[29]._id,
        furnId: furnitures[12]._id,
        name: "شوكولاتة مبطن",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[30]._id,
        furnId: furnitures[13]._id,
        name: "نقشة ذهبية",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[30]._id,
        furnId: furnitures[13]._id,
        name: "نقشة فضية",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[30]._id,
        furnId: furnitures[13]._id,
        name: "دمشقي كريمي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[31]._id,
        furnId: furnitures[13]._id,
        name: "دمشقي نبيذي",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[31]._id,
        furnId: furnitures[13]._id,
        name: "جاكار ذهبي",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[32]._id,
        furnId: furnitures[14]._id,
        name: "أبيض نقي",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[32]._id,
        furnId: furnitures[14]._id,
        name: "رمادي ناعم",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
      {
        fabricId: fabrics[32]._id,
        furnId: furnitures[14]._id,
        name: "بيج",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[33]._id,
        furnId: furnitures[14]._id,
        name: "كتان طبيعي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[33]._id,
        furnId: furnitures[14]._id,
        name: "كتان أبيض",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[34]._id,
        furnId: furnitures[15]._id,
        name: "دمشقي كريمي",
        thumbnail: "/img-4.webp",
        images: ["/img-4.webp"],
      },
      {
        fabricId: fabrics[34]._id,
        furnId: furnitures[15]._id,
        name: "دمشقي رمادي",
        thumbnail: "/img-5.webp",
        images: ["/img-5.webp"],
      },
      {
        fabricId: fabrics[34]._id,
        furnId: furnitures[15]._id,
        name: "دمشقي عاجي",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[35]._id,
        furnId: furnitures[15]._id,
        name: "دمشقي ذهبي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[35]._id,
        furnId: furnitures[15]._id,
        name: "دمشقي فضي",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[36]._id,
        furnId: furnitures[16]._id,
        name: "لؤلؤي",
        thumbnail: "/img-6.webp",
        images: ["/img-6.webp"],
      },
      {
        fabricId: fabrics[36]._id,
        furnId: furnitures[16]._id,
        name: "ذهبي وردي",
        thumbnail: "/img-7.webp",
        images: ["/img-7.webp"],
      },
      {
        fabricId: fabrics[36]._id,
        furnId: furnitures[16]._id,
        name: "شامبانيا",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[37]._id,
        furnId: furnitures[16]._id,
        name: "فضي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[37]._id,
        furnId: furnitures[16]._id,
        name: "وردي خدري",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[38]._id,
        furnId: furnitures[17]._id,
        name: "هندسي فحمي",
        thumbnail: "/img-8.webp",
        images: ["/img-8.webp"],
      },
      {
        fabricId: fabrics[38]._id,
        furnId: furnitures[17]._id,
        name: "هندسي كحلي",
        thumbnail: "/img-9.webp",
        images: ["/img-9.webp"],
      },
      {
        fabricId: fabrics[38]._id,
        furnId: furnitures[17]._id,
        name: "هندسي رمادي",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[39]._id,
        furnId: furnitures[17]._id,
        name: "هندسي أسود",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[39]._id,
        furnId: furnitures[17]._id,
        name: "هندسي أزرق",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[40]._id,
        furnId: furnitures[18]._id,
        name: "زهور وردية",
        thumbnail: "/img-10.webp",
        images: ["/img-10.webp"],
      },
      {
        fabricId: fabrics[40]._id,
        furnId: furnitures[18]._id,
        name: "زهور كريمية",
        thumbnail: "/img-11.webp",
        images: ["/img-11.webp"],
      },
      {
        fabricId: fabrics[40]._id,
        furnId: furnitures[18]._id,
        name: "زهور زرقاء",
        thumbnail: "/img-1.webp",
        images: ["/img-1.webp"],
      },
      {
        fabricId: fabrics[41]._id,
        furnId: furnitures[18]._id,
        name: "زهور خضراء",
        thumbnail: "/img-2.webp",
        images: ["/img-2.webp"],
      },
      {
        fabricId: fabrics[41]._id,
        furnId: furnitures[18]._id,
        name: "زهور وردة",
        thumbnail: "/img-3.webp",
        images: ["/img-3.webp"],
      },
    ]);

    console.log("✅ Seed Finished Successfully");
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
